targets:
  $default:
    sources:
      - lib/**
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|op_builder:
        enabled: true
        options:
          schema: example_bug|lib/graphql/schema.graphql
      gql_build|data_builder:
        enabled: true
        options:
          schema: example_bug|lib/graphql/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: example_bug|lib/graphql/schema.graphql
      ferry_generator|req_builder:
        enabled: true